### ISSUE TITLE
10 seconds delay before callback registers click

### ISSUE THREAD

**Issue by TuningGuide** [lozinsky/typescript-react-mobx-boilerplate#1]
Hi, tomaash recommended me your repo (https://github.com/tomaash/react-example-filmdb/issues/6). I forked it and got it running. But when I load the page and right away click the ++ button nothing happens. It takes arround 10 seconds before the ++ buttons starts working. (Env: Node v6, Firefox v49). Do you know why?

**Comment by lozinsky** [comment]
Excuse please, but I don't know. Project building successfully, without errors? Whether in case of a click there are some messages in the console?

**Comment by TuningGuide** [comment]
I happens only in Firefox, in Chrome it works. I guess I will report it to the mobx team.
