### ISSUE TITLE
root parameter - what used for?

### ISSUE THREAD

**Issue by TuningGuide** [lozinsky/typescript-react-mobx-boilerplate#2]
When I create a new project is asks for a root parameter. What does it stand for?

**Comment by lozinsky** [comment]
Hi. Root parameter this is your id for div element where your react app will be rendered.
For example:

If your root id - "my-app-root", render will be:
```
ReactDOM.render(
	<App />,
	document.getElementById("my-app-root")
);
```

**Comment by TuningGuide** [comment]
Alright, thx

**Comment by TuningGuide** [comment]
Hi, I just updated my boilerplate and saw that you switched from Provider + @inject to directly use the props and pass them further down. Why did you switch? Do you think Provider is bad design? Thx

**Comment by lozinsky** [comment]
Hi. If used provider + @inject, interface with props types for app component will be with optional data. I did not like it, maybe i'm wrong.



On Tue, Oct 4, 2016 at 11:59 AM +0300, "TuningGuide" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I just updated my boilerplate and saw that you switched from Provider + @inject<https://github.com/inject> to directly use the props and pass them further down. Why did you switch? Do you think Provider is bad design? Thx

-
